# -*- coding: utf-8 -*-
"""Calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCDjhcciyJIaP6Hrx5_0kVtbTPG54y3X
"""

# Solicitação do nome do usuário
nome_usuario = input('Para usar a calculadora, digite seu nome: ')
# Mensagem de boas vindas
print(f'Olá, {nome_usuario}, seja bem vindo a nossa calculadora!')
# Solicitação dos algorismos e operações
operacao1 = input('\nDigite a operação que deseja entre os dois algarismos(+,-,*,/,). ')
# Loop para continuar as operações
while operacao1 == '+' or '-' or '*' or '/':
  if operacao1 != '+' and operacao1 != '-' and operacao1 != '*' and operacao1 != '/':
    print('Operação inválida.')
    break
  num1 = float(input('Digite o primeiro número que deseja para a operação: '))
  num2 = float(input('Digite o segundo número que deseja para a operação: '))
  if operacao1 == '+':
    resultado = num1 + num2
  elif operacao1 == '-':
    resultado = num1 - num2
  elif operacao1 == '*':
    resultado = num1 * num2
  elif operacao1 == '/':
    resultado = num1 / num2
# Apresentação do resultado e loop para novas operações
  print('\nO resultado dessa operação é:', (resultado))
  print('Que tal mais algumas contas?')
  operacao1 = input('\nDigite a operação que deseja entre os dois algarismos(+,-,*,/,).')
